# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangebalance',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
