# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fiat',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
