# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:20
from __future__ import unicode_literals

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0006_auto_20171017_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeaccount',
            name='passphrase',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeaccount',
            name='key',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='exchangeaccount',
            name='secret',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
