# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0008_auto_20171024_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangebalance',
            name='most_recent',
            field=models.BooleanField(default=True),
        ),
    ]
