# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0009_exchangebalance_most_recent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangebalance',
            old_name='exchangeAccount',
            new_name='exchange_account',
        ),
    ]
