# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0012_currency_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualinput',
            name='currency',
            field=models.CharField(default='BTC', max_length=50),
        ),
    ]
