# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0013_auto_20171211_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangebalance',
            name='most_recent',
        ),
    ]
