# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0019_addressinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='crypto',
        ),
        migrations.AddField(
            model_name='rates',
            name='crypto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cryptofolio.Currency'),
        ),
        migrations.AddField(
            model_name='rates',
            name='fiat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cryptofolio.Fiat'),
        ),
    ]
