# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0020_auto_20180824_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptofolio.Currency'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='fiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptofolio.Fiat'),
        ),
    ]
