# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0020_auto_20180825_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
