# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptofolio', '0021_auto_20180824_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('fiat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cryptofolio.Fiat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
